# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a77351f6dac0427e10d298b967a4f77"
name = "eco-footprint"
application_url = "https://hot-mom-epson-morris.trycloudflare.com"
embedded = true
handle = "eco-footprint"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://hot-mom-epson-morris.trycloudflare.com/auth/callback", "https://hot-mom-epson-morris.trycloudflare.com/auth/shopify/callback", "https://hot-mom-epson-morris.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
